services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: vehicle_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  backend:
    build: ./backend
    container_name: vehicle_backend
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/vehicles.db:/app/vehicles.db

  worker:
    build: ./worker
    container_name: vehicle_worker
    depends_on:
      - rabbitmq
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    container_name: vehicle_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  rabbitmq_data:
