services:
  backend:
    build: ./backend-simple
    container_name: vehicle_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend-simple/vehicles.db:/app/vehicles.db

  frontend:
    build: ./frontend
    container_name: vehicle_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend